steps:
# Secret Manager から環境変数を取得するステップ
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'fetch-secret'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud secrets versions access latest --secret="OpenAI-API-key-betterChatGpt" > /workspace/openai_api_key.txt
  volumes:
    - name: 'vol'
      path: '/workspace'

# Docker イメージをビルドするステップ
- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  args:
    - 'build'
    - '--build-arg'
    - 'VITE_OPENAI_API_KEY=$(cat /workspace/openai_api_key.txt)'
    - '-t'
    - 'gcr.io/$PROJECT_ID/my-app'
    - '.'
  volumes:
    - name: 'vol'
      path: '/workspace'
images:
  - 'gcr.io/$PROJECT_ID/my-app'
